apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "asdcommon.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.configMap | nindent 2 }}
