apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "asdcommon.labels" $ | indent 4 }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: secondary
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
{{ include "asdcommon.labels" $ | indent 4 }}
  sessionAffinity: None
  type: ClusterIP
